# Generated by Django 4.2 on 2023-04-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='logo',
        ),
        migrations.AddField(
            model_name='event',
            name='event_at',
            field=models.DateTimeField(null=True),
        ),
    ]
