# Generated by Django 4.2 on 2023-04-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_remove_event_logo_event_event_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registration_url',
        ),
        migrations.AddField(
            model_name='event',
            name='has_joined',
            field=models.DateTimeField(null=True),
        ),
    ]
