# Generated by Django 4.2 on 2023-04-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_remove_event_registration_url_event_has_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='has_joined',
        ),
    ]
