# Generated by Django 4.2 on 2023-04-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_alter_join_events_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
