# Generated by Django 4.2 on 2023-04-17 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Events', '0008_alter_join_events_event_alter_join_events_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='join_events',
            options={'default_related_name': 'atendees'},
        ),
        migrations.AlterField(
            model_name='join_events',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.event'),
        ),
        migrations.AlterField(
            model_name='join_events',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
